title: LUMP OF AFFECTION `04
iconURL: assets/default-icon.png
remote_theme: SupunKavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

#social:
#  twitter: _SupunKavinda
#  github: SupunKavinda

plugins:
# - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

#### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N
